export const skillsData = [
    "HTML",
    "CSS",
    "JavaScript",
    "React",
    "Next.js",
    "Node.js",
    "Php",
    "Git",
    "Tailwind",
    "MongoDB",
    "MySQL",
    "Redux",
    "Zustand",
    "Java (basic)",
    "Python",
    "C#",
    "Django",
    "Framer Motion",
    "Locomotive.js",
    "GSAP",
    "GitHub",
] as const;